/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fotogames.gui;

import fotogames.persistencia.entidades.Venda;
import fotogames.persistencia.DAO.VendaDAO;
import fotogames.persistencia.entidades.Venda_Produto;
import fotogames.persistencia.DAO.Venda_ProdutoDAO;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author breno
 */
/**
 * 
 * Classe responsável pela interface gráfica da listagem de vendas.
 */
public class ListagemVenda extends javax.swing.JFrame {

    VendaDAO vDAO = new VendaDAO(); // Objeto para acessar métodos de persistência e consulta de vendas no banco de dados.
    Venda_ProdutoDAO vpDAO = new Venda_ProdutoDAO(); // Objeto para acessar métodos de persistência e consulta de itens vendidos na venda atual.

    /**
     * Método construtor listagemVenda.
     */
    public ListagemVenda() {
        initComponents();
        atualizarTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        String[] colunas = {"Nome", "NF", "Valor", "FormPagamen", "Data"};
        DefaultTableModel tabela = new DefaultTableModel(colunas,0);
        List<Venda> lista = vDAO.listar();
        List<Venda_Produto> listaVP = vpDAO.listar();
        for(int i = 0; i < lista.size(); i++){
            Venda vendaAtual = lista.get(i);
            Venda_Produto vpAtual = listaVP.get(i);
            String[] linha = {
                vendaAtual.getCliente().getNome(),
                String.valueOf(vendaAtual.getNf()),
                String.valueOf(vpAtual.getValorTotal()),
                vendaAtual.getFormPagamento(),
                String.valueOf(vendaAtual.getData())
            };
            tabela.addRow(linha);
        }
        jTable1.setModel(tabela);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListagemVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListagemVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListagemVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListagemVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListagemVenda().setVisible(true);
            }
        });
    }

    /*
    * Método para atualizar tabela.
    */
    public void atualizarTabela() {
        List<Venda> lista = vDAO.listar();
        List<Venda_Produto> listaVP = vpDAO.listar();
        
        
        String[] colunas = {"Nome", "NF", "Valor", "FormPagamen", "Data"};
        
        DefaultTableModel tabela = new DefaultTableModel(colunas, 0);
        
        for (int i = 0; i < lista.size(); i++) {
            Venda vendaAtual = lista.get(i);
            Venda_Produto vpAtual = listaVP.get(i);
            String linha[] ={
                vendaAtual.getCliente().getNome(),
                String.valueOf(vendaAtual.getNf()),
                String.valueOf(vpAtual.getValorTotal()),
                vendaAtual.getFormPagamento(),
                String.valueOf(vendaAtual.getData())
            };
            tabela.addRow(linha);
        }
       
        jTable1.setModel(tabela);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
