/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fotogames.gui;

import fotogames.persistencia.entidades.Funcionario;
import fotogames.persistencia.DAO.FuncionarioDAO;
import javax.swing.JOptionPane;

/**
 *
 * @author breno
 */

/**
 * Classe responsável pela interface gráfica da tela de acesso.
 */
public class TelaInicial extends javax.swing.JFrame {

    FuncionarioDAO fDAO = new FuncionarioDAO(); // Objeto para acessar métodos de persistência e consulta de funcionários no banco de dados.

    /**
     * Método construtor TelaInicial.
     */
    public TelaInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TxLogin = new javax.swing.JTextField();
        TxPassworld = new javax.swing.JPasswordField();
        BtEntrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Foto");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Games");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        TxLogin.setToolTipText("Campo Login");
        TxLogin.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(TxLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 90, -1));
        TxLogin.getAccessibleContext().setAccessibleName("Campo login");
        TxLogin.getAccessibleContext().setAccessibleDescription("Campo para inserir o lgin do funcionário");

        TxPassworld.setToolTipText("Campo senha");
        TxPassworld.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(TxPassworld, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 90, -1));
        TxPassworld.getAccessibleContext().setAccessibleName("Campo senha");
        TxPassworld.getAccessibleContext().setAccessibleDescription("Campo para inserir a senha do funcionário");

        BtEntrar.setBackground(new java.awt.Color(0, 153, 51));
        BtEntrar.setText("Entrar");
        BtEntrar.setToolTipText("Botão entrar");
        BtEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtEntrarActionPerformed(evt);
            }
        });
        jPanel1.add(BtEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 80, -1));
        BtEntrar.getAccessibleContext().setAccessibleDescription("Botão clicável para entra no sistema");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 355, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Ação do botão entrar
     */
    private void BtEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtEntrarActionPerformed
        String login = TxLogin.getText();
        String passworld = fDAO.getMD5(TxPassworld.getText());

        Funcionario func = fDAO.validarAcesso(login, passworld);
        String cargo = func.getCargo();
        if (cargo != null) {
            JOptionPane.showMessageDialog(null, "Bem-Vindo\n" + func.getNome());
            TelaVenda tela = new TelaVenda(func);
            tela.setVisible(true);
            
        }
    }//GEN-LAST:event_BtEntrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtEntrar;
    private javax.swing.JTextField TxLogin;
    private javax.swing.JPasswordField TxPassworld;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
