/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import javax.swing.JOptionPane;
import model.ListaProduto;
import model.Produto;

/**
 *
 * @author breno
 */
public class Estoque extends javax.swing.JFrame {
    TelaEstoque telaEstoque = new TelaEstoque();
    
    /**
     * Creates new form Estoque
     */
    public Estoque(TelaEstoque telaEstoque) {
        initComponents();
        this.telaEstoque = telaEstoque;
        TxCor.setVisible(false);
        TxPlataforma.setVisible(false);
        LbCor.setVisible(false);
        LbPlataforma.setVisible(false);
    }
    
    public Estoque(){
       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        LbTitulo = new javax.swing.JLabel();
        CbJogos = new javax.swing.JCheckBox();
        CbAcessorios = new javax.swing.JCheckBox();
        CbHardware = new javax.swing.JCheckBox();
        TxProduto = new javax.swing.JTextField();
        LbProduto = new javax.swing.JLabel();
        TxFabricante = new javax.swing.JTextField();
        LbFabricante = new javax.swing.JLabel();
        TxQuantidade = new javax.swing.JTextField();
        LbQuantidade = new javax.swing.JLabel();
        LbGarantia = new javax.swing.JLabel();
        TxGarantia = new javax.swing.JTextField();
        TxValor = new javax.swing.JTextField();
        LbValor = new javax.swing.JLabel();
        TxCor = new javax.swing.JTextField();
        LbPlataforma = new javax.swing.JLabel();
        LbCor = new javax.swing.JLabel();
        TxPlataforma = new javax.swing.JTextField();
        BtLimpar = new javax.swing.JButton();
        BtCadastrar = new javax.swing.JButton();
        BtVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        LbTitulo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        LbTitulo.setForeground(new java.awt.Color(0, 0, 0));
        LbTitulo.setText("Catálogo de Produtos");

        buttonGroup1.add(CbJogos);
        CbJogos.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        CbJogos.setText("Jogos");
        CbJogos.setToolTipText("Opção jogo");
        CbJogos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbJogosActionPerformed(evt);
            }
        });

        buttonGroup1.add(CbAcessorios);
        CbAcessorios.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        CbAcessorios.setText("Acessórios");
        CbAcessorios.setToolTipText("Opção Acessórios");
        CbAcessorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbAcessoriosActionPerformed(evt);
            }
        });

        buttonGroup1.add(CbHardware);
        CbHardware.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        CbHardware.setText("Hardware");
        CbHardware.setToolTipText("Opção Hardware");

        TxProduto.setToolTipText("Campo Produto");

        LbProduto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        LbProduto.setForeground(new java.awt.Color(0, 0, 0));
        LbProduto.setText("Produto:");

        TxFabricante.setToolTipText("Campo Fabricante");

        LbFabricante.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        LbFabricante.setForeground(new java.awt.Color(0, 0, 0));
        LbFabricante.setText("Fabricante:");

        TxQuantidade.setToolTipText("Campo Quantidade");

        LbQuantidade.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        LbQuantidade.setForeground(new java.awt.Color(0, 0, 0));
        LbQuantidade.setText("Quantidade:");

        LbGarantia.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        LbGarantia.setForeground(new java.awt.Color(0, 0, 0));
        LbGarantia.setText("Garantia:");

        TxGarantia.setToolTipText("Campo Garantia");

        TxValor.setToolTipText("Campo Valor");

        LbValor.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        LbValor.setForeground(new java.awt.Color(0, 0, 0));
        LbValor.setText("Valor:");

        TxCor.setToolTipText("Campo Cor");

        LbPlataforma.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        LbPlataforma.setForeground(new java.awt.Color(0, 0, 0));
        LbPlataforma.setText("Plataforma:");

        LbCor.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        LbCor.setForeground(new java.awt.Color(0, 0, 0));
        LbCor.setText("Cor:");

        TxPlataforma.setToolTipText("Campo Plataforma");

        BtLimpar.setText("Limpar");
        BtLimpar.setToolTipText("Botão Limpar Campos");

        BtCadastrar.setText("Cadastrar");
        BtCadastrar.setToolTipText("Botão Cadastrar");
        BtCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCadastrarActionPerformed(evt);
            }
        });

        BtVoltar.setText("Voltar");
        BtVoltar.setToolTipText("Botão Voltar");
        BtVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(LbPlataforma)
                                .addGap(18, 18, 18)
                                .addComponent(TxPlataforma, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LbProduto)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(LbGarantia)
                                            .addComponent(LbFabricante, javax.swing.GroupLayout.Alignment.TRAILING))))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TxProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TxFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TxGarantia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(LbCor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TxCor, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(LbQuantidade)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(LbValor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TxValor, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BtVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtCadastrar)
                        .addGap(114, 114, 114)))
                .addGap(30, 30, 30))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(CbHardware)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CbAcessorios)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CbJogos))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(LbTitulo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CbJogos)
                            .addComponent(CbHardware)
                            .addComponent(CbAcessorios)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LbTitulo)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbProduto)
                    .addComponent(TxProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbQuantidade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbFabricante)
                    .addComponent(TxValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbValor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxGarantia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbGarantia))
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxPlataforma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbPlataforma)
                    .addComponent(TxCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbCor))
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtCadastrar)
                    .addComponent(BtLimpar)
                    .addComponent(BtVoltar))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CbAcessoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbAcessoriosActionPerformed
        boolean isSelected = CbAcessorios.isSelected();
        if(isSelected){
        LbCor.setVisible(isSelected);
        TxCor.setVisible(isSelected);
        }else if(!CbAcessorios.isSelected()){
            LbCor.setVisible(false);
            TxCor.setVisible(false);
        }
    }//GEN-LAST:event_CbAcessoriosActionPerformed

    private void BtCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCadastrarActionPerformed
        if(!emptyFields()){
            ListaProduto.adicionar(adicionarProduto());
            JOptionPane.showMessageDialog(rootPane, "Cadastro realizado com sucesso!");
            limpaCampo();            
            telaEstoque.atualizarTabela();
        }
    }//GEN-LAST:event_BtCadastrarActionPerformed

    private void BtVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtVoltarActionPerformed
        dispose();
    }//GEN-LAST:event_BtVoltarActionPerformed

    private void CbJogosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbJogosActionPerformed
       boolean isSelected = CbJogos.isSelected();
       if(isSelected){
       LbPlataforma.setVisible(isSelected);
       TxPlataforma.setVisible(isSelected);
       }else if(!CbJogos.isSelected()){
           LbPlataforma.setVisible(false);
           TxPlataforma.setVisible(false);
       }
    }//GEN-LAST:event_CbJogosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Estoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Estoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Estoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Estoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Estoque().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtCadastrar;
    private javax.swing.JButton BtLimpar;
    private javax.swing.JButton BtVoltar;
    private javax.swing.JCheckBox CbAcessorios;
    private javax.swing.JCheckBox CbHardware;
    private javax.swing.JCheckBox CbJogos;
    private javax.swing.JLabel LbCor;
    private javax.swing.JLabel LbFabricante;
    private javax.swing.JLabel LbGarantia;
    private javax.swing.JLabel LbPlataforma;
    private javax.swing.JLabel LbProduto;
    private javax.swing.JLabel LbQuantidade;
    private javax.swing.JLabel LbTitulo;
    private javax.swing.JLabel LbValor;
    private javax.swing.JTextField TxCor;
    private javax.swing.JTextField TxFabricante;
    private javax.swing.JTextField TxGarantia;
    private javax.swing.JTextField TxPlataforma;
    private javax.swing.JTextField TxProduto;
    private javax.swing.JTextField TxQuantidade;
    private javax.swing.JTextField TxValor;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

        public boolean emptyFields(){
        boolean empty = true;
        
        if(!CbAcessorios.isSelected() && !CbHardware.isSelected() && !CbJogos.isSelected()){
           JOptionPane.showMessageDialog(rootPane, "Selecione Tipo do produto:\n Hardware/Acessórios/Jogos");
           return empty;
        }
        
        
        if(TxProduto.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Informe o produto!");
        }else if(TxGarantia.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(rootPane,"Informe a garantia do produto!");
        }else if(TxFabricante.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Informe o fabricante!");
        }else if(TxValor.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Informe valor do produto!");
        }else if(TxQuantidade.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Informe a quantidade no estoque!");
        }else{
            empty = false;
        }
        return empty;
    }
        public Produto adicionarProduto(){
            Produto produto = new Produto();
            
            try{
            produto.setNome(TxProduto.getText());
            produto.setFabricante(TxFabricante.getText());
            produto.setGarantia(Integer.parseInt(TxGarantia.getText()));
            produto.setValor(Double.parseDouble(TxValor.getText()));
            produto.setQuantidade(Integer.parseInt(TxQuantidade.getText()));
            produto.setPlataforma(TxPlataforma.getText());
            produto.setCor(TxCor.getText());
            } catch(NumberFormatException ex){
                JOptionPane.showMessageDialog(rootPane, "Insira valor do produto corretamente!");
            }
            return produto;
        }
        
        public void limpaCampo(){
            TxProduto.setText("");
            TxGarantia.setText("");
            TxFabricante.setText("");
            TxValor.setText("");
            TxQuantidade.setText("");
            TxPlataforma.setText("");
            TxCor.setText("");
            buttonGroup1.clearSelection();
        }


}
