/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;
import javax.swing.table.DefaultTableModel;
import model.Orcamento;
import model.ListaOrcamento;
import java.util.List;
import javax.swing.JOptionPane;
import model.ListaVenda;
import model.Venda;
/**
 *
 * @author breno
 */
public class HistoricoOrcamento extends javax.swing.JFrame {
    HistoricoOrcamento historico;
    /**
     * Creates new form HistoricoOrcamento
     */
    public HistoricoOrcamento() {
        initComponents();

        atualizarTabela();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        BtCancelar = new javax.swing.JButton();
        BtEfetuar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        String[] colunas = {"Nome", "CPF", "Email", "Telefone", "Pagamento", "Valor"};
        DefaultTableModel tabela = new DefaultTableModel(colunas,0);
        List<Orcamento> lista = ListaOrcamento.listar();
        for(int i = 0; i < lista.size(); i++){
            Orcamento orcamentoAtual = lista.get(i);
            String[] linha = {
                orcamentoAtual.getNome(),
                orcamentoAtual.getCpf(),
                orcamentoAtual.getEmail(),
                orcamentoAtual.getTelefone(),
                orcamentoAtual.getPagamento(),
                orcamentoAtual.getValor()
            };
            tabela.addRow(linha);
        }
        jTable1.setModel(tabela);
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Voltar");
        jButton1.setToolTipText("Campo Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        BtCancelar.setText("Excluir");
        BtCancelar.setToolTipText("Campo Excluir");
        BtCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCancelarActionPerformed(evt);
            }
        });

        BtEfetuar.setText("Efetuar o pedido");
        BtEfetuar.setToolTipText("Campo Registrar Venda");
        BtEfetuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtEfetuarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtEfetuar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(BtCancelar)
                    .addComponent(BtEfetuar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCancelarActionPerformed
        if(posOrcamento() != -1){
            ListaOrcamento.remover(posOrcamento());
            JOptionPane.showMessageDialog(rootPane, "Orçamento excluído com sucesso!");
            atualizarTabela();
        }
    }//GEN-LAST:event_BtCancelarActionPerformed

    private void BtEfetuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtEfetuarActionPerformed
        if(posOrcamento() != -1){
            Orcamento orcamentoSelecionado = ListaOrcamento.getOrcamento(posOrcamento());
            Venda novaVenda = new Venda();
            novaVenda.setNome(orcamentoSelecionado.getNome());
            novaVenda.setCpf(orcamentoSelecionado.getCpf());
            novaVenda.setEmail(orcamentoSelecionado.getEmail());
            novaVenda.setTelefone(orcamentoSelecionado.getTelefone());
            novaVenda.setPagamento(orcamentoSelecionado.getPagamento());
            novaVenda.setValor(orcamentoSelecionado.getValor());
            
            ListaVenda.adicionar(novaVenda);
            ListaOrcamento.remover(posOrcamento());
            atualizarTabela();
        }
    }//GEN-LAST:event_BtEfetuarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HistoricoOrcamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HistoricoOrcamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HistoricoOrcamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HistoricoOrcamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HistoricoOrcamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtCancelar;
    private javax.swing.JButton BtEfetuar;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    public void atualizarTabela(){
       String[] colunas = {"Nome", "CPF", "Email", "Telefone", "Pagamento", "Valor"};
        DefaultTableModel tabela = new DefaultTableModel(colunas,0);
        List<Orcamento> lista = ListaOrcamento.listar();
            for(int i = 0; i < lista.size(); i++){
                Orcamento orcamentoAtual = lista.get(i);
                String[] linha = {
                    orcamentoAtual.getNome(),
                    orcamentoAtual.getCpf(),
                    orcamentoAtual.getEmail(),
                    orcamentoAtual.getTelefone(),
                    orcamentoAtual.getPagamento(),
                    orcamentoAtual.getValor()
        };
            tabela.addRow(linha);
}
            jTable1.setModel(tabela);
    }
    
    public int posOrcamento(){
        int posOrcamento = jTable1.getSelectedRow();
        if(posOrcamento == -1){
            JOptionPane.showMessageDialog(rootPane, "Selecione um orçamento!");
        }
            return posOrcamento;
    }
}
