/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import java.awt.Cursor;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import model.ListaProduto;
import model.ListaVenda;
import model.Produto;
import model.Venda;

/**
 *
 * @author breno
 */
public class TelaVenda extends javax.swing.JFrame {
    List<Produto> listaProduto = ListaProduto.listar();
    ListaVenda listaVenda = new ListaVenda();
    HistoricoVenda historico;
    HistoricoOrcamento orcamento;
    double somaValores = 0.0;
    /**
     * Creates new form TelaVenda
     */
    public TelaVenda(HistoricoVenda historico) {
        initComponents();
        this.historico = historico;
    }
    public TelaVenda(){
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JpCabecalho = new javax.swing.JPanel();
        LbTitulo = new javax.swing.JLabel();
        LbTitulo2 = new javax.swing.JLabel();
        JsLinha = new javax.swing.JSeparator();
        LbVendas = new javax.swing.JLabel();
        LbProdutos = new javax.swing.JLabel();
        LbOrcamento = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        LbTitulo1 = new javax.swing.JLabel();
        BtEfetuar = new javax.swing.JButton();
        LbNome = new javax.swing.JLabel();
        TxNome = new javax.swing.JTextField();
        LbEmail = new javax.swing.JLabel();
        TxEmail = new javax.swing.JTextField();
        LbCpf = new javax.swing.JLabel();
        TxCpf = new javax.swing.JTextField();
        LbTelefone = new javax.swing.JLabel();
        TxTelefone = new javax.swing.JTextField();
        LbValorP = new javax.swing.JLabel();
        LbTotal = new javax.swing.JLabel();
        BtHistorico = new javax.swing.JButton();
        LbPagamento = new javax.swing.JLabel();
        CbPagamento = new javax.swing.JComboBox<>();
        LbProduto = new javax.swing.JLabel();
        TxProduto = new javax.swing.JTextField();
        BtAdicionar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        JpCabecalho.setBackground(new java.awt.Color(0, 102, 153));
        JpCabecalho.setForeground(new java.awt.Color(0, 0, 0));
        JpCabecalho.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LbTitulo.setBackground(new java.awt.Color(0, 0, 0));
        LbTitulo.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        LbTitulo.setForeground(new java.awt.Color(0, 0, 0));
        LbTitulo.setText("Foto");
        LbTitulo.setToolTipText("Nome da Empresa");
        JpCabecalho.add(LbTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 20));

        LbTitulo2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        LbTitulo2.setForeground(new java.awt.Color(0, 0, 0));
        LbTitulo2.setText("Games");
        JpCabecalho.add(LbTitulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 80, 20));
        JpCabecalho.add(JsLinha, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 640, -1));

        LbVendas.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        LbVendas.setForeground(new java.awt.Color(0, 0, 0));
        LbVendas.setText("Venda");
        JpCabecalho.add(LbVendas, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        LbProdutos.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        LbProdutos.setForeground(new java.awt.Color(0, 0, 0));
        LbProdutos.setText("Produtos");
        LbProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LbProdutosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LbProdutosMouseEntered(evt);
            }
        });
        JpCabecalho.add(LbProdutos, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, -1, -1));

        LbOrcamento.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        LbOrcamento.setForeground(new java.awt.Color(0, 0, 0));
        LbOrcamento.setText("Orçamento");
        LbOrcamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LbOrcamentoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LbOrcamentoMouseEntered(evt);
            }
        });
        JpCabecalho.add(LbOrcamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 60, -1, -1));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        JpCabecalho.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, 60, 30));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        JpCabecalho.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 60, 30));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LbTitulo1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        LbTitulo1.setForeground(new java.awt.Color(0, 0, 0));
        LbTitulo1.setText("Centra de Vendas");
        jPanel1.add(LbTitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 13, -1, -1));

        BtEfetuar.setText("Efetuar");
        BtEfetuar.setToolTipText("Botão Efetuar");
        BtEfetuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtEfetuarActionPerformed(evt);
            }
        });
        jPanel1.add(BtEfetuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 260, 79, -1));

        LbNome.setText("Nome:");
        jPanel1.add(LbNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        TxNome.setToolTipText("Campo Nome");
        jPanel1.add(TxNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 131, -1));

        LbEmail.setText("Email:");
        jPanel1.add(LbEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        TxEmail.setToolTipText("Campo Email");
        jPanel1.add(TxEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 131, -1));

        LbCpf.setText("CPF:");
        jPanel1.add(LbCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, -1, -1));

        TxCpf.setToolTipText("Campo CPF");
        jPanel1.add(TxCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, 131, -1));

        LbTelefone.setText("Telefone:");
        jPanel1.add(LbTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, -1, -1));

        TxTelefone.setToolTipText("Campo telefone");
        jPanel1.add(TxTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, 131, -1));

        LbValorP.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        LbValorP.setForeground(new java.awt.Color(0, 0, 0));
        LbValorP.setText("Valor Total:");
        jPanel1.add(LbValorP, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, 80, -1));
        jPanel1.add(LbTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, 70, 17));

        BtHistorico.setText("Historico");
        BtHistorico.setToolTipText("Tela Histórico");
        BtHistorico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtHistoricoActionPerformed(evt);
            }
        });
        jPanel1.add(BtHistorico, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        LbPagamento.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        LbPagamento.setForeground(new java.awt.Color(0, 0, 0));
        LbPagamento.setText("Forma de Pagamento:");
        jPanel1.add(LbPagamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 150, -1));

        CbPagamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Débito", "Crédito" }));
        CbPagamento.setToolTipText("Opções de Pagamento");
        CbPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbPagamentoActionPerformed(evt);
            }
        });
        jPanel1.add(CbPagamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 140, -1));

        LbProduto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        LbProduto.setForeground(new java.awt.Color(0, 0, 0));
        LbProduto.setText("Produto");
        jPanel1.add(LbProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        TxProduto.setToolTipText("Campo Produto");
        TxProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxProdutoActionPerformed(evt);
            }
        });
        jPanel1.add(TxProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 229, -1));

        BtAdicionar.setText("Adicionar");
        BtAdicionar.setToolTipText("Botão Adicionar");
        BtAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtAdicionarActionPerformed(evt);
            }
        });
        jPanel1.add(BtAdicionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 90, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JpCabecalho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JpCabecalho, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LbProdutosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbProdutosMouseEntered
        LbProdutos.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_LbProdutosMouseEntered

    private void LbProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbProdutosMouseClicked
        TelaEstoque telaEstoque = new TelaEstoque();
        telaEstoque.setVisible(true);
    }//GEN-LAST:event_LbProdutosMouseClicked

    private void BtAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtAdicionarActionPerformed
        boolean produtoEncontrado = false;
        for(Produto produto : listaProduto){
            if(produto.getNome().equalsIgnoreCase(TxProduto.getText())){
                somaValores += produto.getValor();
                produtoEncontrado = true;
                break;
            }
            }
        if(produtoEncontrado){
                JOptionPane.showMessageDialog(rootPane, "Produto adicionado com sucesso!");
                LbTotal.setText(String.format("R$ %.2f", somaValores));
                TxProduto.setText("");
            }else{
                JOptionPane.showMessageDialog(rootPane, "Produto não encontrado ou inexistente!");
            }
    }//GEN-LAST:event_BtAdicionarActionPerformed

    private void TxProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxProdutoActionPerformed

    private void CbPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbPagamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CbPagamentoActionPerformed

    private void BtEfetuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtEfetuarActionPerformed
        if(!emptyFields() && validation() == true){
            listaVenda.adicionar(adicionarVenda());
            JOptionPane.showMessageDialog(rootPane, "Venda concluída com sucesso!");
            historico.atualizarTabela();
            limpaCampo();          

        }

    }//GEN-LAST:event_BtEfetuarActionPerformed

    private void BtHistoricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtHistoricoActionPerformed
        HistoricoVenda tela = new HistoricoVenda();
        tela.setVisible(true);
    }//GEN-LAST:event_BtHistoricoActionPerformed

    private void LbOrcamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbOrcamentoMouseClicked
        TelaOrcamento tela = new TelaOrcamento(orcamento);
        tela.setVisible(true);
    }//GEN-LAST:event_LbOrcamentoMouseClicked

    private void LbOrcamentoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbOrcamentoMouseEntered
        LbOrcamento.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_LbOrcamentoMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaVenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtAdicionar;
    private javax.swing.JButton BtEfetuar;
    private javax.swing.JButton BtHistorico;
    private javax.swing.JComboBox<String> CbPagamento;
    private javax.swing.JPanel JpCabecalho;
    private javax.swing.JSeparator JsLinha;
    private javax.swing.JLabel LbCpf;
    private javax.swing.JLabel LbEmail;
    private javax.swing.JLabel LbNome;
    private javax.swing.JLabel LbOrcamento;
    private javax.swing.JLabel LbPagamento;
    private javax.swing.JLabel LbProduto;
    private javax.swing.JLabel LbProdutos;
    private javax.swing.JLabel LbTelefone;
    private javax.swing.JLabel LbTitulo;
    private javax.swing.JLabel LbTitulo1;
    private javax.swing.JLabel LbTitulo2;
    private javax.swing.JLabel LbTotal;
    private javax.swing.JLabel LbValorP;
    private javax.swing.JLabel LbVendas;
    private javax.swing.JTextField TxCpf;
    private javax.swing.JTextField TxEmail;
    private javax.swing.JTextField TxNome;
    private javax.swing.JTextField TxProduto;
    private javax.swing.JTextField TxTelefone;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
    
    public boolean emptyFields(){
        boolean empty = true;
        if(TxNome.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Informe seu Nome!");
        }else if(TxCpf.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(rootPane,"Informe seu CPF!");
        }else if(TxEmail.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Informe seu Email!");
        }else if(TxTelefone.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Informe seu Telefone!");
        }else if(CbPagamento.getSelectedItem().toString().equals("Selecione")){
            JOptionPane.showMessageDialog(rootPane, "Selecione uma forma de pagamento!");
        }else if(LbTotal.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Para efetuar a compra precisa adicionar 1 produto!");
        }else{
            empty = false;
        }
        return empty;
    }

    public Venda adicionarVenda(){        
        Venda venda = new Venda();
        venda.setNome(TxNome.getText());
        venda.setEmail(TxEmail.getText());
        venda.setCpf(TxCpf.getText());
        venda.setTelefone(TxTelefone.getText());
        venda.setPagamento(CbPagamento.getSelectedItem().toString());
        venda.setValor(LbTotal.getText());
        return venda;
    }

    public boolean validation(){
        boolean validation = true;
        if(!TxCpf.getText().matches("[0-9]{3}[.][0-9]{3}[.][0-9]{3}[-][0-9]{2}")){
            JOptionPane.showMessageDialog(rootPane, "Campo CPF Inválido: xxx.xxx.xxx-xx");
            return validation = false;
        }else if(!TxEmail.getText().matches("[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}")){
            JOptionPane.showMessageDialog(rootPane, "Formato de E-mail inválido!");
            return validation = false;
        }else if(!TxTelefone.getText().matches("[0-9]{11}")){
            JOptionPane.showMessageDialog(rootPane, "Campo Telefone Inválido: DDDxxxxxxxxx");
            return validation = false;
        }else{
            return validation;
        }
    }
    
    public void limpaCampo(){
        TxNome.setText("");
        TxCpf.setText("");
        TxEmail.setText("");
        TxTelefone.setText("");
        CbPagamento.setSelectedIndex(0);
        LbTotal.setText("");
    }
}
