/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import java.util.List;
import javax.swing.JOptionPane;
import model.ListaOrcamento;
import model.ListaProduto;
import model.Orcamento;
import model.Produto;
import model.Venda;

/**
 *
 * @author breno
 */
public class TelaOrcamento extends javax.swing.JFrame {
    HistoricoOrcamento orcamento;
    double somaValores = 0.0;
    List<Produto> listaProduto = ListaProduto.listar();
    ListaOrcamento listaOrcamento = new ListaOrcamento();
    /**
     * Creates new form TelaOrcamento
     */
    public TelaOrcamento(HistoricoOrcamento orcamento) {
        initComponents();
        this.orcamento = orcamento;
    }
    
    public TelaOrcamento(){
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        LbNome = new javax.swing.JLabel();
        LbTelefone = new javax.swing.JLabel();
        LbEmail = new javax.swing.JLabel();
        LbCpf = new javax.swing.JLabel();
        LbTitulo = new javax.swing.JLabel();
        TxNome = new javax.swing.JTextField();
        TxEmail = new javax.swing.JTextField();
        TxTelefone = new javax.swing.JFormattedTextField();
        TxCpf = new javax.swing.JFormattedTextField();
        LbPagamento = new javax.swing.JLabel();
        CbPagamento = new javax.swing.JComboBox<>();
        BtHistorico = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TxProduto = new javax.swing.JTextField();
        BtAdicionar = new javax.swing.JButton();
        LbValor = new javax.swing.JLabel();
        LbValorTotal = new javax.swing.JLabel();
        TxRegistrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        LbNome.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        LbNome.setForeground(new java.awt.Color(0, 0, 0));
        LbNome.setText("Nome:");

        LbTelefone.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        LbTelefone.setForeground(new java.awt.Color(0, 0, 0));
        LbTelefone.setText("Telefone:");

        LbEmail.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        LbEmail.setForeground(new java.awt.Color(0, 0, 0));
        LbEmail.setText("Email:");

        LbCpf.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        LbCpf.setForeground(new java.awt.Color(0, 0, 0));
        LbCpf.setText("CPF:");

        LbTitulo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        LbTitulo.setForeground(new java.awt.Color(0, 0, 0));
        LbTitulo.setText("Central de Orçamentos");

        TxNome.setToolTipText("Campo Nome");

        TxEmail.setToolTipText("Campo Email");

        TxTelefone.setToolTipText("Campo Telefone");

        TxCpf.setToolTipText("Campo CPF");

        LbPagamento.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        LbPagamento.setForeground(new java.awt.Color(0, 0, 0));
        LbPagamento.setText("Forma de Pagamento:");

        CbPagamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Débito", "Crédito" }));
        CbPagamento.setToolTipText("Opções de Pagamento");

        BtHistorico.setText("Historico");
        BtHistorico.setToolTipText("Tela Histórico");
        BtHistorico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtHistoricoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(LbEmail)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(LbNome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxNome, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LbTelefone)
                            .addComponent(LbCpf))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TxTelefone, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                            .addComponent(TxCpf))
                        .addGap(32, 32, 32))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(LbPagamento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CbPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(BtHistorico))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addComponent(LbTitulo)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LbTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtHistorico)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LbCpf, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TxCpf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LbEmail)
                            .addComponent(TxEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LbTelefone)
                            .addComponent(TxTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LbPagamento)
                            .addComponent(CbPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LbNome)
                            .addComponent(TxNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Produto");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        TxProduto.setToolTipText("Campo Produto");
        jPanel3.add(TxProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 180, -1));

        BtAdicionar.setText("Adicionar");
        BtAdicionar.setToolTipText("Botão Adicionar");
        BtAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtAdicionarActionPerformed(evt);
            }
        });
        jPanel3.add(BtAdicionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, -1, -1));

        LbValor.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        LbValor.setForeground(new java.awt.Color(0, 0, 0));
        LbValor.setText("Valor:");
        jPanel3.add(LbValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, -1, -1));

        LbValorTotal.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel3.add(LbValorTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, 80, 20));

        TxRegistrar.setText("Registrar");
        TxRegistrar.setToolTipText("Botão registrar Orçamento");
        TxRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxRegistrarActionPerformed(evt);
            }
        });
        jPanel3.add(TxRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, 90, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtAdicionarActionPerformed
        boolean produtoEncontrado = false;
        for(Produto produto : listaProduto){
            if(produto.getNome().equalsIgnoreCase(TxProduto.getText())){
                somaValores += produto.getValor();
                produtoEncontrado = true;
                break;
            }
            }
        if(produtoEncontrado){
                JOptionPane.showMessageDialog(rootPane, "Produto adicionado com sucesso!");
                LbValorTotal.setText(String.format("R$ %.2f", somaValores));
                TxProduto.setText("");
            }else{
                JOptionPane.showMessageDialog(rootPane, "Produto não encontrado ou inexistente!");
            }
    }//GEN-LAST:event_BtAdicionarActionPerformed

    private void BtHistoricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtHistoricoActionPerformed
        HistoricoOrcamento tela = new HistoricoOrcamento();
        tela.setVisible(true);
    }//GEN-LAST:event_BtHistoricoActionPerformed

    private void TxRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxRegistrarActionPerformed
        if(!emptyFields() && validation()){
            listaOrcamento.adicionar(adicionarOrcamento());
            JOptionPane.showMessageDialog(rootPane, "Orçamento feito com sucesso!");
            limpaCampo();
        }
    }//GEN-LAST:event_TxRegistrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaOrcamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaOrcamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaOrcamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaOrcamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaOrcamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtAdicionar;
    private javax.swing.JButton BtHistorico;
    private javax.swing.JComboBox<String> CbPagamento;
    private javax.swing.JLabel LbCpf;
    private javax.swing.JLabel LbEmail;
    private javax.swing.JLabel LbNome;
    private javax.swing.JLabel LbPagamento;
    private javax.swing.JLabel LbTelefone;
    private javax.swing.JLabel LbTitulo;
    private javax.swing.JLabel LbValor;
    private javax.swing.JLabel LbValorTotal;
    private javax.swing.JFormattedTextField TxCpf;
    private javax.swing.JTextField TxEmail;
    private javax.swing.JTextField TxNome;
    private javax.swing.JTextField TxProduto;
    private javax.swing.JButton TxRegistrar;
    private javax.swing.JFormattedTextField TxTelefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables

        public boolean emptyFields(){
        boolean empty = true;
        if(TxNome.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Informe seu Nome!");
        }else if(TxCpf.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(rootPane,"Informe seu CPF!");
        }else if(TxEmail.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Informe seu Email!");
        }else if(TxTelefone.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Informe seu Telefone!");
        }else if(CbPagamento.getSelectedItem().toString().equals("Selecione")){
            JOptionPane.showMessageDialog(rootPane, "Selecione uma forma de pagamento!");
        }else if(LbValorTotal.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Para efetuar a compra precisa adicionar 1 produto!");
        }else{
            empty = false;
        }
        return empty;
    }

        public boolean validation(){
        boolean validation = true;
        if(!TxCpf.getText().matches("[0-9]{3}[.][0-9]{3}[.][0-9]{3}[-][0-9]{2}")){
            JOptionPane.showMessageDialog(rootPane, "Campo CPF Inválido: xxx.xxx.xxx-xx");
            return validation = false;
        }else if(!TxEmail.getText().matches("[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}")){
            JOptionPane.showMessageDialog(rootPane, "Formato de E-mail inválido!");
            return validation = false;
        }else if(!TxTelefone.getText().matches("[0-9]{11}")){
            JOptionPane.showMessageDialog(rootPane, "Campo Telefone Inválido: DDDxxxxxxxxx");
            return validation = false;
        }else{
            return validation;
        }
    }
        public void limpaCampo(){
        TxNome.setText("");
        TxCpf.setText("");
        TxEmail.setText("");
        TxTelefone.setText("");
        CbPagamento.setSelectedIndex(0);
        LbValorTotal.setText("");
        somaValores = 0.0;
    }
        public Orcamento adicionarOrcamento(){        
        Orcamento orcamento = new Orcamento();
        orcamento.setNome(TxNome.getText());
        orcamento.setEmail(TxEmail.getText());
        orcamento.setCpf(TxCpf.getText());
        orcamento.setTelefone(TxTelefone.getText());
        orcamento.setPagamento(CbPagamento.getSelectedItem().toString());
        orcamento.setValor(LbValorTotal.getText());
        return orcamento;
    }
}
