/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import javax.swing.JOptionPane;
import telas.HistoricoVenda;
/**
 *
 * @author breno
 */
public class TelaInicial extends javax.swing.JFrame {
    HistoricoVenda historico = new HistoricoVenda();
    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
        JOptionPane.showMessageDialog(rootPane, "Usuário teste!\n ACESSO: usuario\n SENHA: 12345");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPAcesso = new javax.swing.JPanel();
        LbTitulo = new javax.swing.JLabel();
        LbTitulo2 = new javax.swing.JLabel();
        BtEntrar = new javax.swing.JButton();
        TxUsuario = new javax.swing.JTextField();
        PfSenha = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JPAcesso.setBackground(new java.awt.Color(0, 102, 153));
        JPAcesso.setForeground(new java.awt.Color(0, 0, 0));
        JPAcesso.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LbTitulo.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        LbTitulo.setForeground(new java.awt.Color(0, 0, 0));
        LbTitulo.setLabelFor(LbTitulo2);
        LbTitulo.setText("Foto");
        LbTitulo.setToolTipText("Nome da Empresa");
        JPAcesso.add(LbTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        LbTitulo2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        LbTitulo2.setForeground(new java.awt.Color(0, 0, 0));
        LbTitulo2.setText("Games");
        LbTitulo2.setToolTipText("Nome da Empresa");
        JPAcesso.add(LbTitulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        BtEntrar.setBackground(new java.awt.Color(0, 153, 51));
        BtEntrar.setText("Entrar");
        BtEntrar.setToolTipText("Botão entrar");
        BtEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtEntrarActionPerformed(evt);
            }
        });
        JPAcesso.add(BtEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 80, -1));
        BtEntrar.getAccessibleContext().setAccessibleDescription("Botão para entrar no aplicativo");

        TxUsuario.setToolTipText("Campo Usuário");
        TxUsuario.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        JPAcesso.add(TxUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 90, -1));
        TxUsuario.getAccessibleContext().setAccessibleName("Usuário");
        TxUsuario.getAccessibleContext().setAccessibleDescription("Campo para adicionar o usuário");

        PfSenha.setToolTipText("Campo Senha");
        PfSenha.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        JPAcesso.add(PfSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 90, -1));
        PfSenha.getAccessibleContext().setAccessibleName("Senha");
        PfSenha.getAccessibleContext().setAccessibleDescription("Campo para adicionar a senha");

        jLabel1.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        jLabel1.setText("Esqueceu a senha?");
        JPAcesso.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 414, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JPAcesso, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPAcesso, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtEntrarActionPerformed
        if(TxUsuario.getText().equalsIgnoreCase("usuario") && PfSenha.getText().equals("12345")){
        TelaVenda tela = new TelaVenda(historico);
        tela.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(rootPane, "Usuário ou senha inválida\n ACESSO TESTE: usuario\n SENHA: 12345");
        }
    }//GEN-LAST:event_BtEntrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtEntrar;
    private javax.swing.JPanel JPAcesso;
    private javax.swing.JLabel LbTitulo;
    private javax.swing.JLabel LbTitulo2;
    private javax.swing.JPasswordField PfSenha;
    private javax.swing.JTextField TxUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
